image: silex/emacs:master-dev

before_script:
  - apt-get update && apt-get install -y rsync

stages:
  - build
  - github

build:
  stage: build
  script:
    - ./mirror-elpa .ci/github.config
  only:
    - master

gihub:
  stage: github
  script:
    - git push --mirror "https://${GITHUB_USER}:${GITHUB_ACCESS_TOKEN}@github.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git" >/dev/null 2>&1
  only:
    - master
