* =mirror-elpa=

(To) Mirror Emacs Lisp package archives. Used to create and maintain mirrors
under Git repository.

Available mirrors:

- [[https://github.com/d12frosted/elpa-mirror][elpa-mirror - GitHub]]
- [[https://gitlab.com/d12frosted/elpa-mirror][elpa-mirror - GitLab]]

Note that currently only GitLab and GitHub are supported out of box as a remote
for the mirror. Though you can use =mirror-elpa= to maintain local mirror or
mirror on any other Git hosting. See ~Usage~ section for more information.

** Prerequisites

The following software must be installed on your system:

- Git
- Emacs
- rsync

** Usage

In order to use =mirror-elpa= script, you need to prepare configuration file.
You can do it manually or use =configure= script provided by this repository.
Example of configuration file:

#+begin_src bash
  mirror_path="$XDG_CACHE_HOME/elpa-mirror"
  mirror_host="github.com"
  mirror_owner="d12frosted"
  mirror_repo="elpa-mirror"
  access_login="$ACCESS_LOGIN"
  access_token="$ACCESS_TOKEN"
  commit_name="Golem"
  commit_email="golem@d12frosted.io"
  elpa_clone_path="$XDG_CACHE_HOME/elpa-clone"

  function git_config_hook {
    git config commit.gpgsign false
  }
#+end_src

Some explanations:

1. =mirror_path= is location of mirror repository on your disk.
2. =mirror_host=, =mirror_owner= and =mirror_repo= used to build url to your
   remote mirror repository. Repository URL is build like this:
   #+begin_src bash
     mirror_url="https://${access_login}:${access_token}@${mirror_host}/${mirror_owner}/${mirror_repo}.git"
   #+end_src
3. =access_login= is user with access to repository.
4. =access_token= is password/secret/token that is used for authentication. On
   GitHub and GitLab you can create access tokens and use them (which is
   recommended).
5. =commit_name= and =commit_email= used as committer information.
6. =elpa_clone_path= is location of =elpa_clone= script for Emacs.

The configuration wizard is not maintained, but you can give it a try, as it
should help you with token creation.

#+begin_src bash
  ./configure
#+end_src

** Using with CRON

#+BEGIN_SRC bash
$ ./configure
$ make install
#+END_SRC

You can also specify how often to sync mirror when running make install
(defaults to every 4 hours) and location to resulting configuration file
(defaults to =$XDG_CONFIG_HOME/mirror-elpa.sh=:

#+BEGIN_SRC bash
$ make install SCHEDULE="0 0 * * *" CONFIG_FILE="~/mirror-elpa.sh"
#+END_SRC

=SCHEDULE= can be set to any valid [[https://en.wikipedia.org/wiki/Cron#CRON_expression][CRON expression]].

** Credits

- [[https://github.com/dochang][Desmond O. Chang]], thanks for [[https://github.com/dochang/elpa-clone][elpa-clone]].
- [[https://github.com/ninrod][Filipe Silva]], thanks for keeping this project alive.
- [[https://github.com/alyssais][Alyssa Ross]], thanks for [[https://github.com/alyssais/humans][humans]] project that inspired me for improving my
  existing scripts into this project.
