#!/usr/bin/env bash

set -ue

GITHUB_REPO_URL="https://${GITHUB_USER}:${GITHUB_ACCESS_TOKEN}@github.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"

git push --mirror "$GITHUB_REPO_URL" >/dev/null 2>&1
